### ISSUE TITLE
System.parse() interface

### ISSUE THREAD

**Issue by marco-buttu** [discos/simulators#1]
The `System.parse()` method takes a byte as argument and returns:

* `False` when the byte is not the header and it is still waiting for the header
* `True` when it has already got the header and it is composing the message
* the reponse, a non empty string, when there is a response to send back to the client

If the system has nothing to send to the client, as in the case of brodcast requests, `System.parse()` should return `True`.

It eventually raises a `ValueError` in case there is an unexpected error (not considered by the protocol).

**Comment by Corpse89Grinder** [comment]
ValueError now is raised only in case of unknown protocol command. Still looking for additional events.

**Comment by marco-buttu** [comment]
The requirement is now implemented in the server.  The `System.parse()`  has to use this specification.
