### ISSUE TITLE
Active surface drivers startup/restart delay causing issues.

### ISSUE THREAD

**Issue by Corpse89Grinder** [discos/simulators#13]
As described in the active surface [documentation file](https://drive.google.com/open?id=0BwE1Lqvi9-FNSDVsel84N3hUbTA), drivers complete the startup/restart procedure in about 100ms. The feature is currently implemented in [active_surface.py](https://github.com/discos/simulators/blob/master/simulators/active_surface.py) but as result of unit testing, it is causing issues.

**Comment by Corpse89Grinder** [comment]
Partially fixed with [8607752](https://github.com/discos/simulators/commit/860775267fbeec806d7d48fc9722193297d2c118). The current implementation of the System class now gets an optional driver startup delay parameter, expressed in seconds of inactivity after each reboot. Default parameter value is now set to 0s, but the actual startup delay should be 0.1s.

**Comment by Corpse89Grinder** [comment]
Fixed with #16

**Comment by marco-buttu** [comment]
The active surface component does not send a `reset` command to the drivers, except in special cases (for instance, after a driver power down).  For the simulation porpuse there is no need to use the real delay of 100ms.  Giving this delay as a argument to the `System`, we can still run the protocol unit test fast, and we are also able to run the simulator as it actually behaves, just instantiating `System(driver_reset_delay=0.1)`.
