### ISSUE TITLE
Installation steps in user documentation

### ISSUE THREAD

**Issue by marco-buttu** [discos/simulators#206]
The installation process has to be written in the user documentation.

**Comment by giuseppe-carboni** [comment]
I don't know why it is not displayed in readthedocs, but the setup process is already been documented as you can see [here](https://github.com/discos/simulators/tree/master/doc). The process is written in the `setup.rts` file, which is also included in the `index.rst` document. This has to be investigated properly.

**Comment by marco-buttu** [comment]
There was no webhook from github to readthedocs. I added one but it is still not working. I keep this issue open until we fix the webhook issue.

**Comment by giuseppe-carboni** [comment]
Fixed by updating readthedocs webhook
