### ISSUE TITLE
Add #LOADCONF and #CONF? commands to GAIA board simulator

### ISSUE THREAD

**Issue by giuseppe-carboni** [discos/simulators#256]
@marco-buttu I will send you more details about this issue in private

**Comment by marco-buttu** [comment]
Description in [this file](https://github.com/discos/simulators/files/8646671/Documento.sulle.modifiche.del.firmware.di.GAIA.20220408.docx).

**Comment by marco-buttu** [comment]
Fixed in commit 43d5e9b453d531bb48c409dc4cf9797768e9ae0a.
