### ISSUE TITLE
Revise GAIA protocol

### ISSUE THREAD

**Issue by marco-buttu** [discos/simulators#258]
The LNAs of new receivers are going to be monitored and controlled by a board called GAIA, described in [this internal report](https://github.com/discos/simulators/files/8590570/Internal.Report.GAIA.pdf). The document explains the UDP request/response protocol to be implemented to communicate with the board. Each command has an header (usually `#`) and a terminator (newline byte `\n`). The bytes are mean to be ASCII characters. The response has an header, the value to be returned, and a terminator byte. For instance, in the following case the client sends `commadA` and gets `X` as a response:

`Request: #commandA\n`
`Response: #X\n`

This issue is intended for discussing about some problems that can occour with the current protocol definition, and possible solutions and improvements.

Problem 01: I do not get any response
---------------------------------------------------
The client sends `commandA` and waits for the response. After a bit the response is not arrived yet. The client can only guess about what is appening: eather `commandA` has been lost before reaching the board, or the response has been lost, or the board is going to answer at some point, or the board will never answer because is not working properly. But the client can not wait forever and it has to take a decision. It decides to send again `commandA`, and finally it gets a response, `#10\n`. After that it sends `commandB` and gets `#9\n`. That is the sequence of commands and answers, in chronological order from the client point of view:

```
1) request: #commandA\n
2) request: #commandA\n
3) response: #10\n
4) response: #9\n
```

The client assumed that `10` was related to the second request `commandA`, but `10` was actually the response to the first request. In fact the board was working properly and at some point it replied but the response arrived to the client with a delay. So, in addition the client decided that `9` was the answer to `commandB`, but it was actually the answer to the second `commandA`. It is starting to be a mess... 

**Solution**

Every request has an integer `id` and the response keeps the `id` of the request. Andrea Saba would like to have the `id` located at the end of the message, with a value between `0` and `1023`, and to keep the syntax described in the [internal report](https://github.com/discos/simulators/files/8590570/Internal.Report.GAIA.pdf) where the parameters are separated by spaces. To summarize, here is a request (with parameters `x` and `Y`) and response:

`#command X Y id\n ---> #VALUE id\n`

**Comment by aorlati** [comment]
I do not expect much traffic between GAIA boards and DISCOS so desync issues should be very rare, though extending the protocol by adding a command ID will get rid of it completely. Is there a particular reason to limit the ID 0...1023?

**Comment by sabahome** [comment]
There aren't no particular reason to limit the ID range. If necessary this range can be extended to [0, 16383]

**Comment by giuseppe-carboni** [comment]
Since there not seems to be any limitation on the ID range, I suggest using the UNIX time (could be down to milli or microsecond precision, in integer format). This will also provide the time information for each command that was sent to the device. If, for any reason, this is unfeasible, a simple ID will be fine.

**Comment by sabahome** [comment]
The UNIX time is a long number. I prefer to avoid the use of double with a MCU with 8bit.

**Comment by giuseppe-carboni** [comment]
While this is true, consider you don't really have to convert it, you can leave it as an array of bytes and send it back as it is. Again, if this is not feasible because of computing/RAM limitation, let's stick to a simple integer ID

**Comment by sabahome** [comment]
To meet the performance requirement for laboratory use the ID will be a string consisting exclusively of numeric characters [0 ... 9]. the length of the string will be between 1 and 12 characters. A zero (0) character sequence will be valid. Absence of the ID will not execute the command and will return an error string. Only the * IDN? can be run with or without ID.

**Comment by marco-buttu** [comment]
Ok @sabahome, that's fine for me.

**Comment by marco-buttu** [comment]
@sabahome Andrea, [this document](https://github.com/discos/simulators/files/8651719/Documento.sulle.modifiche.del.firmware.di.GAIA.20220408.docx) describes the error management in the following way:

*Il comando #LOADCONF restituisce il valore x nel caso in cui il caricamento sia andato a buon fine; restituisce zero nel caso in cui il caricamento non sia andato a buon fine, per esempio nel caso in cui non sia presente una configurazione x salvata.*

As reported in the [Internal Report GAIA.pdf](https://github.com/discos/simulators/files/8651748/Internal.Report.GAIA.pdf), in case of error it should return (instead of 0) a string `ERROR(error_code) [detail](detailDEC)`.

Please let me know what `error_code`, `detail` and `detailDEC` you want to use. Thank you, Marco

**Comment by sabahome** [comment]
Ok. In case of error the `#LOADCONF` will return a specific `error_code` (`ERROR_ON_LOAD_CONF`), as usual `detail `and `detailDEC` are used only for debugging.

**Comment by marco-buttu** [comment]
@sabahome thank you
