### ISSUE TITLE
CARUSO w-band improvement to meet compliance with the updated protocol

### ISSUE THREAD

**Issue by LorenzoMonti** [discos/simulators#322]

**Comment by giuseppe-carboni** [comment]
@LorenzoMonti can this be closed? I see you merged the relative branch. A suggestion, in order for GitHub to automatically close the issues when merging a branch, refer the issue on the title of the pull request as 'Fix #322 [...]' instead of 'Fix issue #322 [...]'.

**Comment by LorenzoMonti** [comment]
@giuseppe-carboni thanks for the tips. I would like to wait to have confirmation that the protocol with UKRI is the definitive one. Is it better to close this issues and make another one just in case?

**Comment by giuseppe-carboni** [comment]
Oh, no, feel free to keep it open as long as you need.

**Comment by giuseppe-carboni** [comment]
Seems like a single line was not covered, but I don't really understand why, @LorenzoMonti do you have any idea how this happened?
https://app.codecov.io/gh/discos/simulators/commit/67918b0292332c27294dea21783cb7fc38b16047#1c98773336ca4dbf385f223a678d2bba-R126

**Comment by LorenzoMonti** [comment]
It's true, I'm just working on it. I don't understand it either, the test about that exists: https://github.com/discos/simulators/blob/master/tests/test_lo.py#L200
Could it be a bug?

**Comment by giuseppe-carboni** [comment]
Seems like #334 fixed this, although there's still something to do:
[here](https://github.com/discos/simulators/blob/73bfaf05801eea16c8d38373eba8dbccfbd94f89/simulators/lo/w_LO.py#L122), this function should return the string 'Int.' whenever the reference is set to 'INT' and 'Ext.' whenever the reference is set to 'EXT'. The same applies to [this function](https://github.com/discos/simulators/blob/73bfaf05801eea16c8d38373eba8dbccfbd94f89/simulators/lo/w_LO.py#L125).
