### ISSUE TITLE
Simulator for the SRT C-band Receiver

### ISSUE THREAD

**Issue by aorlati** [discos/simulators#336]
This simulator should be added. I already posted a preliminary control component: https://github.com/discos/discos/commit/3acecd1e9bfd96d6bf1f52e6289a195a401acac1
I ask for assistance.

**Comment by marco-buttu** [comment]
Is it possible to link here the documentation about commands/protocol or whatever required for the simulator?

**Comment by aorlati** [comment]
@marco-buttu , I'm still collecting documentation from receivers group. They are finalizing the document right now. At the moment I can say that the Dewar and the LNA control boards are exactly the same (protocol and mapping) as the 7GHz. I tested the code on the receiver and everything seems to work just fine. The C-band has a third control board (2IF) with some more receiver configuration, The protocol will be the same but for everything else we need the technical document.
In the mean time we can just add the simulation of the two (known) boards, I think we can duplicate the 7GHz simulator.
