### ISSUE TITLE
Write the whole AS simulator

### ISSUE THREAD

**Issue by marco-buttu** [discos/simulators#49]
Write the whole AS simulator:  it must instantiate 96 servers.

**Comment by jjpopski** [comment]
Could Docker be a tool to do this?

**Comment by marco-buttu** [comment]
@jjpopski thanks for you interest :-)  Where to run the simulators (in an isolated docker container, in a VMs, in a phisical machine, ecc.) should be a different topic that we will see later.  This issue is just about writing the code to run the simulator, no matter where.  We currently have a server agnostic of the configuration, and now we need that configuration and a *running procedure* to instantiate it 96 times, one instance for each AS line. This should be a generic running procedure, because we wrote a framework for that, and we will use it not just for the AS but also for all future simulators.
